language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-mgo' ]; then cd .. && eval "mv $currentfolder generator-mgo" && cd generator-mgo; fi

